version: '3'

services:
  admin:
    image: ghcr.io/romaxa55/v2ray-web-manager/admin:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR: ./vpn-admin/target/admin*.jar
        JAR_PATH: /app/admin.jar
    environment:
      ADMIN_EMAIL: admin@admin.com
      ADMIN_PASSWORD: 123456
      PROXY_AUTH_PASSWORD: ""
      SMTP_HOST: ""
      SMTP_USERNAME: ""
      SMTP_PASSWORD: ""
      SMTP_PORT: ""
      SMTP_STARTTLS_ENABLED: "false"
      LOGGING_FILE_PATH: conf/admin.log
      SERVER_PORT: 9091
      TOMCAT_MAX_THREADS: 5
      TOMCAT_MIN_THREADS: 2
      DB_PATH: /app/admin.db
      HIKARI_MAX_POOL_SIZE: 5
      HIKARI_MIN_IDLE: 2
      LOGGING_LEVEL_ROOT: info
    ports:
      - "9091:9091"

  proxy:
    image: ghcr.io/romaxa55/v2ray-web-manager/proxy:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR: ./proxy/target/v2ray-proxy-*.jar
        JAR_PATH: /app/v2ray-proxy.jar
    environment:
      ADMIN_EMAIL: admin@admin.com
      ADMIN_PASSWORD: 123456
      PROXY_AUTH_PASSWORD: ""
      SMTP_HOST: ""
      SMTP_USERNAME: ""
      SMTP_PASSWORD: ""
      SMTP_PORT: ""
      SMTP_STARTTLS_ENABLED: "false"
      LOGGING_FILE_PATH: conf/admin.log
      SERVER_PORT: 9091
      TOMCAT_MAX_THREADS: 5
      TOMCAT_MIN_THREADS: 2
      DB_PATH: /app/admin.db
      HIKARI_MAX_POOL_SIZE: 5
      HIKARI_MIN_IDLE: 2
      LOGGING_LEVEL_ROOT: info
    ports:
      - "9091:9091"