version: '3'

services:
  admin:
    image: ghcr.io/romaxa55/iptv-proxy/admin:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR: ./vpn-admin/target/admin*.jar
        JAR_PATH: /app/admin.jar
        ENTRYPOINY: ./docker/admin_entrypoint.sh
    ports:
      - "9091:9091"
