version: '3'

services:
  admin:
    image: ghcr.io/romaxa55/v2ray-web-manager/admin:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR: ./vpn-admin/target/admin*.jar
        JAR_PATH: /app/admin.jar
        SCRIPT: ./docker/admin_config.sh
        SCRIPT_BIN: admin_cfg
    environment:
      ADMIN_EMAIL: admin@admin.com
      ADMIN_PASSWORD: 123456
      PROXY_AUTH_PASSWORD: "ChangeMe"
      SMTP_HOST: ""
      SMTP_USERNAME: ""
      SMTP_PASSWORD: ""
      SMTP_PORT: ""
      SMTP_STARTTLS_ENABLED: "false"
      LOGGING_FILE_PATH: /var/log/admin.log
      SERVER_PORT: 9091
      TOMCAT_MAX_THREADS: 5
      TOMCAT_MIN_THREADS: 2
      DB_PATH: /app/db/admin.db
      HIKARI_MAX_POOL_SIZE: 5
      HIKARI_MIN_IDLE: 2
      LOGGING_LEVEL_ROOT: info
    volumes:
      - ./conf:/app/db/
    ports:
      - "9091:9091"

  proxy:
    image: ghcr.io/romaxa55/v2ray-web-manager/proxy:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR: ./proxy/target/v2ray-proxy-*.jar
        JAR_PATH: /app/v2ray-proxy.jar
        SCRIPT: ./docker/proxy_config.sh
        SCRIPT_BIN: proxy_cfg
    environment:
      PROXY_AUTH_PASSWORD: 'ChangeMe'
      PROXY_LOCAL_PORT: 8081
      PROXY_MAX_CONNECTIONS: 300
      LOGGING_FILE_PATH: /var/logs/v2ray-proxy.log
      LOGGING_FILE_MAX_HISTORY: 7
      LOGGING_LEVEL_ROOT: info
      MANAGER_ADDRESS: http://127.0.0.1:9091
      SERVER_PORT: 8091
      TOMCAT_MAX_THREADS: 1
      TOMCAT_MIN_THREADS: 1
    ports:
      - "8091:8091"
