on:
  push:
    branches:
      - master
  workflow_dispatch:

name: Maven Release

jobs:
  build:
    name: Maven Release Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Java Maven release
        uses: qcastel/github-actions-maven-release@v1.12.39
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          version-patch: true
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"
          maven-servers: ${{ env.MVN_REPO_SERVERS }}
          docker-registry-id: ghcr.io
          docker-registry-username: git
          docker-registry-password: ${{ secrets.GITHUB_TOKEN }}
        env:
          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
          MVN_REPO_SERVERS: '[{"id": "github", "username": "git", "password": "${{ secrets.GITHUB_TOKEN }}"}]'