on:
  push:
    branches:
      - develop

name: Create GitHub Release

jobs:
  build:
    name: GitHub Release Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - run: mvn --batch-mode --update-snapshots package
      - run: mkdir staging && cp ./**/target/*.jar staging

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Admin Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ghcr.io/romaxa55/v2ray-web-manager/admin:${{ github.ref_name }}
          build-args: |
            JAR=./vpn-admin/target/admin*.jar
            JAR_PATH=/app/admin.jar
            SCRIPT=./docker/admin_config.sh
            SCRIPT_BIN=admin_cfg

      - name: Build and push Proxy Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ghcr.io/romaxa55/v2ray-web-manager/proxy:${{ github.ref_name }}
          build-args: |
            JAR=./proxy/target/v2ray-proxy-*.jar
            JAR_PATH=/app/proxy.jar
            SCRIPT=./docker/proxy_config.sh
            SCRIPT_BIN=proxy_cfg