on:
  push:
    branches:
      - master
  workflow_dispatch:
  

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Java Maven release
#        uses: qcastel/github-actions-maven-release@v1.12.31
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#          version-patch: true
#        env:
#          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
#
#      - name: Maven Jar Publish
#        uses: eric2788/maven-jar-publish@v3
#