on:
  push:
    branches:
      - master
  workflow_dispatch:
  

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Java Maven release
        uses: qcastel/github-actions-maven-release@v1.12.39
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          version-patch: true
          docker-registry-id: ghcr.io
          docker-registry-username: romaxa55
          docker-registry-password: ${{ secrets.GITHUB_TOKEN }}
        env:
          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
