on:
  push:
    branches:
      - master
  workflow_dispatch:
  

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Java Maven release
        uses: qcastel/github-actions-maven-release@v1.12.39
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          version-patch: true
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"
          maven-servers: ${{ env.MVN_REPO_SERVERS }}
          docker-registry-id: ghcr.io
          docker-registry-username: git
          docker-registry-password: ${{ secrets.GITHUB_TOKEN }}
        env:
          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
          MVN_REPO_SERVERS: '[{"id": "github", "username": "git", "password": "${{ secrets.GITHUB_TOKEN }}"}]'

      - run: mkdir staging && cp ./**/target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
          retention-days: 1
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.run_number }}"
          title: "Automated Build ${{ github.run_number }}"
          prerelease: false
          files: staging/*.jar