on:
  push:
    branches:
      - master
  workflow_dispatch:
  

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Java Maven release
        uses: qcastel/github-actions-maven-release@v1.12.31
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          version-patch: true
        env:
          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            *.jar