on:
  push:
    tags:
      - '*'

name: Create GitHub Release

jobs:
  build:
    name: GitHub Release Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - run: mvn --batch-mode --update-snapshots package
      - run: mkdir staging && cp ./**/target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
          retention-days: 1

      - uses: scottbrenner/generate-changelog-action@master
        id: Changelog

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.ref_name }}
          title: "${{ github.ref_name }}"
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          files: staging/*.jar
          draft: false
          prerelease: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push admin
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/386,linux/ppc64le,linux/s390x
          push: true
          tags: ghcr.io/romaxa55/v2ray-web-manager/admin:${{ github.ref_name }}
          build-args: |
            JAR=./vpn-admin/target/admin*.jar
            JAR_PATH=/app/admin.jar
            ENTRYPOINT=./docker/admin_entrypoint.sh

