on:
  push:
    branches:
      - develop

name: Create GitHub Release

jobs:
  build:
    name: GitHub Release Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - run: mvn --batch-mode --update-snapshots package
      - run: mkdir staging && cp ./**/target/*.jar staging

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: KengoTODA/actions-setup-docker-compose@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


