on:
  push:
    branches:
      - develop

name: Create GitHub Release

jobs:
  build:
    name: GitHub Release Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - run: mvn --batch-mode --update-snapshots package
      - run: mkdir staging && cp ./**/target/*.jar staging

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push admin
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/admin:${{ github.ref_name }}
          build-args: |
            BUILDKIT_MULTI_PLATFORM=1
            JAR=./vpn-admin/target/admin*.jar
            JAR_PATH=/app/admin.jar
            ENTRYPOINT=./docker/admin_entrypoint.sh


